### ISSUE TITLE
Playing audio streams

### ISSUE THREAD

**Issue by Caoimhin89** [ericdaugherty/alexa-skills-kit-golang#4]
I see that there is a struct called "Directive" where an Stream can be set, but how do I set the Directives for the Response?

**Comment by ericdaugherty** [comment]
Directive is an attribute on the Response object.  You should be able to
create a directive with a child AudioItem that specifies the URL.

I can add a convenience method, but for now, you can do something like:

    response.Directives[0] = alexa.Directives{
        Type: "AudioPlayer.Play",
        PlayBehavior: "REPLACE_ALL",
        AudioItem: {
            Stream: {
                Token: "track2-long-audio",
                URL: "
https://my-audio-hosting-site.com/audio/sample-song-2.mp3",
                OffsetInMilliseconds: 0,
            },
        },
    }

**Comment by ericdaugherty** [comment]
Scratch that. I pushed an update to add an 'AddAudioPlayer' convenience method. Just call that on the response.

**Comment by Caoimhin89** [comment]
Awesome, thank you!
